feat: use a generated intermediate address as the forwarder
cosmos/ibc-apps pull request #72
Opened 2023-07-26 08:59 UTC by javiersuweijie

This PR replaces https://github.com/cosmos/ibc-apps/pull/69. Instead of enforce the usage of the module account as the intermediate forwarder, PMF will generate an address based on the sender's address.

This method has the following advantages:
1. Receiver is able to verify where the message came from by perform the intermediate address generation method
2. When a chain does not have PFM installed, the message will fallback to the receiving account which is assumed to be controlled by the sender.

2023-07-26 16:07 UTC, agouin requested changes

2023-07-26 16:07 UTC, agouin commented on middleware/packet-forward-middleware/router/keeper/keeper.go
> +		hostAccAddr, err := sdk.AccAddressFromBech32(feePayer)
the `intermediateSender` should be the fee payer here, as that is where the funds are received, and will be forwarded out of.

2023-07-26 16:07 UTC, agouin commented on middleware/packet-forward-middleware/router/keeper/keeper.go
> +	// Handle backward compatibility for inflight packets right after the middleware upgrade
this is not necessary when the fee payer is the `intermediateSender`

2023-07-26 16:07 UTC, agouin commented on middleware/packet-forward-middleware/router/keeper/keeper.go
> +	feePayer string,
we shouldn't need to separate `feePayer` and `intermediateSender`

2023-07-26 16:17 UTC, agouin commented on middleware/packet-forward-middleware/router/types/params.go
> +	IntermediateAddrPrefix = "packet-fowarder"
```suggestion
	IntermediateAddrPrefix = "packet-forwarder"
```

2023-07-26 16:40 UTC, nicolaslara commented on middleware/packet-forward-middleware/router/keeper/keeper.go
> +	feePayer string,
Why is this called fee payer? AFAIK the fee is paid by the relayer everywhere except for the initial send

2023-07-26 16:43 UTC, nicolaslara commented on middleware/packet-forward-middleware/router/keeper/keeper.go
> +	feePayer string,
oh, I see! this is in the case where there is a forwarding fee. Interesting 🤔 I wonder if any chain has the fees enabled.

2023-07-27 03:47 UTC, javiersuweijie commented
Thanks @agouin. Somehow I thought the fee payer was going to pay in the native token existing in the account instead of using the amount that was transferred. This makes a lot more sense. Thanks for the review.

2023-07-27 03:49 UTC, javiersuweijie commented
Since the changes here are the same as https://github.com/cosmos/ibc-apps/pull/71 closing this in favour of that.

2023-07-27 03:49 UTC, closed without merging